TASK-59433: Rename file : accentuated charachters aren't saved
exoplatform/documents pull request #469
Opened 2022-09-07 16:42 UTC by hchaabene

**prior to change**: when i rename a file method **cleanName()** ignore the special character and convert it  **by (_)**
Fix : i try to skip that method when renaming the file.

2022-09-09 13:31 UTC, ahamdi requested changes

2022-09-09 13:31 UTC, ahamdi commented on documents-storage-jcr/src/main/java/org/exoplatform/documents/storage/jcr/JCRDocumentFileStorage.java
> -      String name = Text.escapeIllegalJcrChars(cleanString(title));
we should not remove cleanString here, instead, we need just to clean the content name and preserve the title as is.

2022-09-14 11:51 UTC, azayati approved these changes
LGTM

2022-09-14 14:07 UTC, ahamdi approved these changes

2022-09-14 14:07 UTC, merged