fix: fix No version in the history version drawer if a file is duplicated : EXO-61044
exoplatform/documents pull request #612
Opened 2022-12-01 13:37 UTC by GouadriaHanen

prior to this change, after duplicating a document, the history version drawer is empty since no version is added
after this change, an auto version is added after creating a document

2022-12-01 17:29 UTC, ahamdi requested changes

2022-12-01 17:29 UTC, ahamdi commented on pom.xml
> +      <dependency>
Could you import the parent POM of ECMS instead ?

2022-12-01 17:29 UTC, ahamdi commented on documents-storage-jcr/src/test/java/org/exoplatform/documents/storage/jcr/JCRDocumentFileStorageTest.java
> +    when(autoVersionService.autoVersion(any(Node.class))).thenReturn(null);
This instruction not needed IMO, you will just spy on the autoVersionService to check if the function was called, it won't be called really.

2022-12-01 17:39 UTC, GouadriaHanen commented on pom.xml
> +      <dependency>
done!

2022-12-01 17:39 UTC, GouadriaHanen commented on documents-storage-jcr/src/test/java/org/exoplatform/documents/storage/jcr/JCRDocumentFileStorageTest.java
> +    when(autoVersionService.autoVersion(any(Node.class))).thenReturn(null);
done

2022-12-01 19:06 UTC, ahamdi approved these changes

2022-12-01 19:08 UTC, merged

2022-12-01 19:29 UTC, hbenali commented on pom.xml
> +        <version>${org.exoplatform.ecms.version}</version>
Wrong property name Use `addon.exo.ecms.version` instead. cc @ahamdi

2022-12-06 04:50 UTC, hakermi commented
Ecms dependancy is not allowed in documents app