fix: remove ecms dependency and rework the history version for duplicated file - EXO-61044
exoplatform/documents pull request #619
Opened 2022-12-08 15:34 UTC by GouadriaHanen

prior to this change, after duplicating a document, the history version drawer is empty since no version is added
after this change, an auto version is added after duplicating a document

2022-12-08 17:27 UTC, ahamdi requested changes

2022-12-08 17:27 UTC, ahamdi commented on documents-storage-jcr/src/main/java/org/exoplatform/documents/storage/jcr/JCRDocumentFileStorage.java
> +      autoVersion(newNode);
COuld you use org.exoplatform.services.jcr.ext.utils.VersionHistoryUtils#createVersion to create the new version ?

2022-12-08 17:27 UTC, ahamdi commented on documents-storage-jcr/src/test/java/org/exoplatform/documents/storage/jcr/JCRDocumentFileStorageTest.java
>      verify(sessionProvider, times(1)).close();
we need to asssert that the file is already versioned

2022-12-09 09:59 UTC, ahamdi commented on documents-storage-jcr/src/main/java/org/exoplatform/documents/storage/jcr/JCRDocumentFileStorage.java
> +
this is no more needed right ?

2022-12-09 10:02 UTC, GouadriaHanen commented on documents-storage-jcr/src/main/java/org/exoplatform/documents/storage/jcr/JCRDocumentFileStorage.java
> +
yes removed !

2022-12-09 10:07 UTC, ahamdi approved these changes
LGTM

2022-12-09 10:09 UTC, merged