fix: fix the 3 dots menu actions are not immediatly displayed after the creation of a folder - EXO-62146
exoplatform/documents pull request #747
Opened 2023-02-08 08:01 UTC by IlhemEssaadi

Prior this change, not all actions in the 3 dots menu are available after creating a folder. After this change, all actions are available, this has been fixed by adding the method of refreshing files after creating a new folder.

2023-02-10 11:25 UTC, ahamdi submitted a review, later dismissed

2023-02-13 10:23 UTC, ahamdi approved these changes

2023-02-13 10:27 UTC, ahamdi requested changes
After a second thought looking at the source code, could you avoid reloading files from backend ?

2023-02-14 12:38 UTC, ahamdi requested changes

2023-02-14 12:38 UTC, ahamdi commented on documents-webapp/src/main/webapp/vue-app/documents/components/DocumentsMain.vue
> +          this.refreshFiles();
Couldn't we avoid this call ?

2023-02-14 14:02 UTC, IlhemEssaadi commented on documents-webapp/src/main/webapp/vue-app/documents/components/DocumentsMain.vue
> +          this.refreshFiles();
> Couldn't we avoid this call ?

Done !

2023-02-14 14:46 UTC, ahamdi approved these changes

2023-02-14 14:50 UTC, merged