fix : Enable to move a folder in a certain cases -EXO-62663
exoplatform/documents pull request #780
Opened 2023-02-24 13:47 UTC by sofyenne

To sort folders, we use `NumberUtils.isNumber()` library to check if the folder or file name is a number taht can be compared. 
However in some cases we may have a specific document name like  `12f` or `12L` which is considered a valid number in java , as result the `isNumber` method return true but if we try to parse this number we received a `numberFormatException` because this number format cannot be parsed.
To handle this exception we need to replace the `isNumber` method with `isParsable` method.

2023-02-24 15:23 UTC, ahamdi requested changes
Coud you add a Unit test for this change ?

2023-02-27 13:54 UTC, sofyenne commented
> Coud you add a Unit test for this change ?

Done !

2023-02-27 15:03 UTC, ahamdi commented on documents-storage-jcr/src/test/java/org/exoplatform/documents/storage/jcr/JCRDocumentFileStorageTest.java
> +    assertEquals(NumberUtils.isParsable(folderWithSpecificName1.getName()),false);
No need to test ```NumberUtils.isParsable()```

2023-02-27 15:15 UTC, sofyenne commented on documents-storage-jcr/src/test/java/org/exoplatform/documents/storage/jcr/JCRDocumentFileStorageTest.java
> +    assertEquals(NumberUtils.isParsable(folderWithSpecificName1.getName()),false);
done !

2023-02-27 15:34 UTC, ahamdi approved these changes

2023-02-27 16:42 UTC, merged