fix: [Document] sort rules are not respected during filter by name and extended search - EXO-62937.
exoplatform/documents pull request #804
Opened 2023-03-13 16:03 UTC by akhanfir

Prior to this change,the filter by name in the list of document files and extended search is not working properly. After this changes, this list of document files displays the workflows correctly.

2023-03-20 15:55 UTC, rdenarie requested changes
The pr have conflict, can you update ?

Can you also rework the commit message ?
In your message, you have this 

> Prior to this change,the filter by name in the list of document files and extended search is not working properly
It does not explain WHY the filter not working. Please try to answer question WHY

and this :

> After this changes, this list of document files displays the workflows correctly.
It does not explain HOW you fix the problem. Please try to reword by answering the question HOW.

Finally, you try to fix the problem by sorting the search result list, after the search. 
But, in documentSearchServiceConnector, we pass options sortField and sortDirection. So the result list should be sorted by the search connector. 

In addition, my IDE show this 
![image](https://user-images.githubusercontent.com/807839/226396200-7be5a66e-608d-4cb3-b938-910975e0b700.png)

The sortField and sortDirection are not used in the search function. I think it could be better to use it in the ES query, so that ES is in charge of sorting the result, and we get already sorted results, no need to recompute it.

2023-03-24 07:16 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-03-24 07:33 UTC, rdenarie requested changes
Can you rebase the pr

2023-03-24 08:02 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-03-24 08:22 UTC, exo-swf commented
Your PR triggers too many exo-ci builds! Please finish your work and then, set your PR ready! Thank you

2023-03-24 08:58 UTC, rdenarie requested changes

2023-03-24 08:58 UTC, rdenarie commented on documents-storage-jcr/src/main/java/org/exoplatform/documents/storage/jcr/search/DocumentSearchServiceConnector.java
> +    }
if sortField is title, you must sort on title.raw

2023-03-24 12:45 UTC, rdenarie approved these changes

2023-03-24 12:45 UTC, merged