fix: Prevent group administrators from being displayed in the access management drawer for non-group administrator members - EXO-64412
exoplatform/documents pull request #926
Opened 2023-05-22 17:18 UTC by sofyenne

This change is going to prevent group administrators from being displayed in the access management drawer for non-group administrator members .

2023-05-23 09:38 UTC, ahamdi requested changes

2023-05-23 09:38 UTC, ahamdi commented on documents-storage-jcr/src/main/java/org/exoplatform/documents/storage/jcr/util/JCRDocumentsUtil.java
> +          if (membershipEntry.toString().equals("*:/platform/administrators") && !aclIdentity.isMemberOf(membershipEntry)) {
```suggestion
          UserACL userACL = CommonsUtils.getService(UserACL.class);
          if (membershipEntry.getGroup().equals(userACL.getAdminGroups()) && !aclIdentity.isMemberOf(membershipEntry)) {
```

2023-05-24 08:19 UTC, sofyenne commented on documents-storage-jcr/src/main/java/org/exoplatform/documents/storage/jcr/util/JCRDocumentsUtil.java
> +          if (membershipEntry.toString().equals("*:/platform/administrators") && !aclIdentity.isMemberOf(membershipEntry)) {
done !

2023-05-24 08:51 UTC, ahamdi approved these changes

2023-05-24 09:33 UTC, merged